name: hypnose-behavior
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12,<3.13
  - numpy<2
  - pandas
  - pyarrow
  - matplotlib
  - scipy
  - tqdm
  - pillow
  - ipython
  - ipywidgets
  - ipykernel
  - ipympl
  - pyyaml
  - opencv         
  - dotmap         
  - pip
  - pip:
    - moviepy
    - swc-aeon==0.1.0
    - harp-python
    - -e ../hypnose-helpers
    - -e .